Show_top_section_for_staff_only:
  type: bool
  default: false
  description: 
    en: "Show the top section of the navigation menu for staff only."
  
Show_top_section_for_logged-in_only:
  type: bool
  default: false
  description: 
    en: "Show the top section of the navigation menu for only logged-in users."
  
Hide_top_section_for_all:
  type: bool
  default: false
  description: 
    en: "Hide the top section of the navigation menu from all users."
    
Show_more_for_staff_only:
  type: bool
  default: false
  description: 
    en: "Show the more drop-down section of the navigation menu for staff only."
  
Show_more_for_logged-in_only:
  type: bool
  default: false
  description: 
    en: "Show the more section of the navigation menu for only logged-in users."

Show_anniversaries_for_staff_only:
  type: bool
  default: false
  description: 
    en: "Show the Anniversaries link in the More section for staff only, if you have the cakeday plugin installed. Only logged-in users can view by default."

Show_anniversaries_for_staff_only:
  type: bool
  default: false
  description: 
    en: "Show the Birthdays link in the More section for staff only, if you have the cakeday plugin installed. Only logged-in users can view by default."

Show_Docs_for_staff_only:
  type: bool
  default: false
  description: 
    en: "Show the Docs link in the More section for staff only, if you have the Docs plugin installed. Only logged-in users can view by default."

Show_categories_for_staff_only:
  type: bool
  default: false
  description: 
    en: "Show the Categories section for staff only."
  
Show_categories_for_logged-in_only:
  type: bool
  default: false
  description: 
    en: "Show the Categories section for logged-in users only."

Show_tags_for_staff_only:
  type: bool
  default: false
  description: 
    en: "Show the Tags section for staff only."
  
Show_tags_for_logged-in_only:
  type: bool
  default: false
  description: 
    en: "Show the Tags section for logged-in users only."

Show_messages_for_staff_only:
  type: bool
  default: false
  description: 
    en: "Show the Messages section for staff only."
  
Show_messages_for_logged-in_only:
  type: bool
  default: false
  description: 
    en: "Show the Messages section for logged-in users only."   

Show_channels_for_staff_only:
  type: bool
  default: false
  description: 
    en: "Show the Channels section for staff only."
  
Show_channels_for_logged-in_only:
  type: bool
  default: false
  description: 
    en: "Show the Channels section for logged-in users only."

Show_personaL_chat_for_staff_only:
  type: bool
  default: false
  description: 
    en: "Show the Personal Chat section for staff only."
  
Show_personal_chat_for_logged-in_only:
  type: bool
  default: false
  description: 
    en: "Show the Personal Chat section for logged-in users only."

Anon_menu_section:
  type: string
  default: "anon-menu-name"
  description:
    en: "Custom section to show for only for anonymous (not-logged-in) users. Use all lowercase and dashes for spaces (ie: Anon Menu = anon-menu). Always visible to staff."

User_menu_section:
  type: string
  default: "user-menu-name"
  description:
    en: "Custom section to show for logged-in users only. Use all lowercase and dashes for spaces (ie: User Menu = user-menu)."

Show_navigation_menu_to_logged-in_only:
  type: bool
  default: false
  description: 
    en: "Show navigation menu for only logged-in users (hide the entire side-bar from anonymous users)."  
