show_these_sections_for_staff_only:
  type: enum
  default: ""
  choices:
    - community
    - categories
    - tags
    - messages
    - chat-channels
    - chat-dms
  description: 
    en: "Show these navigation sidebar sections for staff only."
  
  show_these_sections_for_logged-in_only:
  type: enum
  default: ""
  choices:
    - community
    - categories
    - tags
    - messages
    - chat-channels
    - chat-dms
  description: 
    en: "Show these navigation sidebar sections for logged-in only (hide from anon users)."

show_these_links_for_staff_only:
  type: enum
  default: ""
  choices:
    - everything
    - my-posts
    - anniversaries
    - birthdays
    - docs
    - badges
    - users
    - about
  description: 
    en: "Show these navigation sidebar links for staff only."
  
  show_these_links_for_logged-in_only:
  type: enum
  default: ""
  choices:
    - everything
    - my-posts
    - anniversaries
    - birthdays
    - docs
    - badges
    - users
    - about
  description: 
    en: "Show these navigation sidebar links for logged-in users only (hide from anon users)."

show_more_for_staff_only:
  type: bool
  default: false
  description:
    en: "Show More drop-down section for staff only."

show_more_for_logged-in_only:
  type: bool
  default: false
  description:
    en: "Show More drop-down section for logged-in users only (hide from anon users)."

show_custom_for_staff_only:
  type: string
  default: "staff-menu"
  description:
    en: "Custom section to show for only for staff users. Use all lowercase and dashes for spaces (ie: Staff Menu = staff-menu)."

show_custom_for_logged-in_only:
  type: string
  default: "user-menu"
  description:
    en: "Custom section to show for logged-in users only. Use all lowercase and dashes for spaces (ie: User Menu = user-menu)."

show_custom_for_anon_only:
  type: string
  default: "anon-menu"
  description:
    en: "Custom section to show for only for anonymous (not-logged-in) users. Use all lowercase and dashes for spaces (ie: Anon Menu = anon-menu)."

show_navigation_menu_to_logged-in_only:
  type: bool
  default: false
  description:
    en: "Show entire navigation menu for only logged-in users (hide the entire side-bar from anon users)."
