show_these_sections_for_staff_only:
  type: list
  default: chat-channels|chat-dms|custom-staff-menu
  description: 
    en: "Show these navigation sidebar sections for staff only. Can use default or custom sections. Use lower-case section names with dashes for spaces."
  
show_these_sections_for_logged-in_only:
  type: list
  default: community|categories|tags|custom-user-menu
  description: 
    en: "Show these navigation sidebar sections for logged-in only (hide from anon users). Can use default or custom sections."

show_these_links_for_staff_only:
  type: list
  default: anniversaries|birthdays|users|custom-staff-link
  description: 
    en: "Show these navigation sidebar links for staff only. Can use defaults or custom links. Use lower-case link names with dashes for spaces."
  
show_these_links_for_logged-in_only:
  type: list
  default: everything|docs|badges|about|faq|custom-user-link
  description: 
    en: "Show these navigation sidebar links for logged-in users only (hide from anon users). Can use defaults or custom links."

show_more_for_staff_only:
  type: bool
  default: false
  description:
    en: "Show More drop-down section for staff only. Overrides More links display where relevant."

show_more_for_logged-in_only:
  type: bool
  default: false
  description:
    en: "Show More drop-down section for logged-in users only (hide from anon users). Above setting cannot be enabled. Overrides More links display where relevant."

show_custom_for_anon_only:
  type: string
  default: "anon-menu"
  description:
    en: "Custom section to show for only for anonymous (not-logged-in) users. Use all lowercase and dashes for spaces (ie: Anon Menu = anon-menu)."

hide_custom_menus_globe_icon:
  type: bool
  default: false
  description:
    en: "Hide the custom menu globe icon from staff (this setting only affects staff, since non-staff cannot see the globe by default)."

show_navigation_menu_to_logged-in_only:
  type: bool
  default: false
  description:
    en: "Show entire navigation menu for only logged-in users (hide the entire menu from anon users)."

default_menu_section_ordering:
  type: list
  list_type: simple
  default: categories|tags|messages|chat-dms|chat-channels
  description: 
    en: "Use the arrow buttons to move the default menu sections up and down to put them in the order they should appear in the navigation sidebar menu. Does not apply to custom menu sections."
  
